Prepare docker

diff --git a/Dockerfile.dev b/Dockerfile.dev
--- a/Dockerfile.dev
+++ b/Dockerfile.dev
@@ -22,20 +22,36 @@ RUN apt-get install -y wget git tmux ripgrep curl unzip neovim
 RUN wget https://raw.githubusercontent.com/marcelocra/.dotfiles/master/unix/.tmux.conf -P ~
 
 # ------------------------------------------------------------------------------
-# - dotNET ---------------------------------------------------------------------
+# - dotnet ---------------------------------------------------------------------
 # ------------------------------------------------------------------------------
-# Download, install and configure.
-ENV DOTNET_ROOT=$HOME/dotnet
-ENV DOTNET_FILE="dotnet-sdk-7.0.100-linux-x64.tar.gz"
+# Install dotnet 6.0
+ENV DOTNET_6_ROOT=$HOME/dotnet6
+ENV DOTNET_6_FILE="dotnet-sdk-6.0.403-linux-x64.tar.gz"
 RUN wget \
-  "https://download.visualstudio.microsoft.com/download/pr/253e5af8-41aa-48c6-86f1-39a51b44afdc/5bb2cb9380c5b1a7f0153e0a2775727b/${DOTNET_FILE}"
-RUN [ "$(sha512sum $DOTNET_FILE | tr ' ' '\n' | head -n1)" = "0a2e74486357a3ee16abb551ecd828836f90d8744d6e2b6b83556395c872090d9e5166f92a8d050331333d07d112c4b27e87100ba1af86cac8a37f1aee953078" ] \
+  "https://download.visualstudio.microsoft.com/download/pr/1d2007d3-da35-48ad-80cc-a39cbc726908/1f3555baa8b14c3327bb4eaa570d7d07/${DOTNET_6_FILE}"
+RUN [ "$(sha512sum $DOTNET_6_FILE | tr ' ' '\n' | head -n1)" = "779b3e24a889dbb517e5ff5359dab45dd3296160e4cb5592e6e41ea15cbf87279f08405febf07517aa02351f953b603e59648550a096eefcb0a20fdaf03fadde" ] \
   && echo "success - valid shasum" \
   || (echo "failure - invalid shasum" && exit 1)
-RUN mkdir -p $DOTNET_ROOT && tar zxf $DOTNET_FILE -C $DOTNET_ROOT
-ENV PATH="${PATH}:${DOTNET_ROOT}"
-RUN rm $DOTNET_FILE
+RUN mkdir -p $DOTNET_6_ROOT && tar zxf $DOTNET_6_FILE -C $DOTNET_6_ROOT
+RUN rm $DOTNET_6_FILE
+
+# Install dotnet 7.0
+ENV DOTNET_7_ROOT=$HOME/dotnet7
+ENV DOTNET_7_FILE="dotnet-sdk-7.0.100-linux-x64.tar.gz"
+RUN wget \
+  "https://download.visualstudio.microsoft.com/download/pr/253e5af8-41aa-48c6-86f1-39a51b44afdc/5bb2cb9380c5b1a7f0153e0a2775727b/${DOTNET_7_FILE}"
+RUN [ "$(sha512sum $DOTNET_7_FILE | tr ' ' '\n' | head -n1)" = "0a2e74486357a3ee16abb551ecd828836f90d8744d6e2b6b83556395c872090d9e5166f92a8d050331333d07d112c4b27e87100ba1af86cac8a37f1aee953078" ] \
+  && echo "success - valid shasum" \
+  || (echo "failure - invalid shasum" && exit 1)
+RUN mkdir -p $DOTNET_7_ROOT && tar zxf $DOTNET_7_FILE -C $DOTNET_7_ROOT
+RUN rm $DOTNET_7_FILE
+
+# Point PATH to generic dotnet root.
+ENV DOTNET_ROOT=$HOME/bin/dotnet
+ENV PATH="$PATH:$DOTNET_ROOT"
+RUN ln -s $DOTNET_7_ROOT $DOTNET_ROOT
 ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
+
 
 # ------------------------------------------------------------------------------
 # - Additional stuff -----------------------------------------------------------
@@ -44,3 +60,4 @@ ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
 # there's a need to update other things above, then move these ones to a more
 # appropriate location.
 WORKDIR ${HOME}
+
